# BoltVulnScanner Configuration File

# Global settings
scan_timeout: 30
max_retries: 3
user_agent: "BoltVulnScanner/0.1.0"

# Crawler settings
crawler:
  max_depth: 3
  max_pages: 100
  same_domain_only: true
  exclude_regex: []
  delay: 1.0  # seconds between requests
  max_requests_per_sec: 5

# Port scanner settings
ports:
  default_range: "1-1000"
  top_ports: [21, 22, 23, 25, 53, 80, 110, 111, 135, 139, 143, 443, 993, 995, 1723, 3306, 3389, 5900, 8080, 8443]
  concurrency: 100
  timeout: 3

# XSS settings
xss:
  payloads:
    - "<script>alert('XSS')</script>"
    - "javascript:alert('XSS')"
    - "<img src=x onerror=alert('XSS')>"
  demo_payload: "<!--XSS-DEMO-->"
  confirm_attempts: 3

# SQLi settings
sqli:
  error_based_payloads:
    - "' OR '1'='1"
    - "\" OR \"1\"=\"1"
  boolean_based_payloads:
    - "' AND '1'='2"
    - "\" AND \"1\"=\"2"
  time_based_payloads:
    - "'; WAITFOR DELAY '00:00:05'--"
    - "\"; SELECT pg_sleep(5)--"
  demo_payload: "' OR '1'='1--"

# Directory enumeration settings
dir_enum:
  wordlist: "default_wordlist.txt"
  extensions: [".bak", ".old", ".backup", ".txt", ".log"]
  concurrency: 20
  timeout: 10

# TLS check settings
tls:
  min_version: "TLSv1.2"
  weak_ciphers: 
    - "RC4"
    - "MD5"
    - "EXPORT"

# Default wordlist for directory enumeration
wordlist_default:
  - "admin"
  - "login"
  - "backup"
  - "config"
  - "test"
  - "dev"
  - "api"
  - "dashboard"
  - "upload"
  - "downloads"
  - "images"
  - "css"
  - "js"
  - "tmp"
  - "temp"